global:
  imageRegistry: npindusdirectacr.azurecr.io
  imagePullSecrets:
    - name: npindussecret

image:
  repository: grafana/grafana
  tag: "12.3.0"

sidecar:
  image:
    repository: kiwigrid/k8s-sidecar
    tag: "1.30.9"

adminUser: admin
adminPassword: admin

ingress:
  enabled: true
  ingressClassName: npindusdirect-ingress
  path: /
  pathType: Prefix
  hosts:
    - no-loki.example.com
  tls:
    - secretName: idirect-tlssecret-new
      hosts:
        - np-loki.example.com

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        access: proxy
        url: http://loki-gateway.loki.svc.cluster.local/
        isDefault: true
        jsonData:
          httpHeaderName1: X-Scope-OrgID
        secureJsonData:
          httpHeaderValue1: loki
