global:
  imageRegistry: npindusdirectacr.azurecr.io
  imagePullSecrets:
    - name: npindussecret

image:
  repository: grafana/promtail
  tag: "3.5.1"

config:
  clients:
    - url: http://loki-gateway.loki.svc.cluster.local/loki/api/v1/push
      tenant_id: loki
